menu:
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}

email: 'yan427 AT purdue.edu'

social:
- {icon: 'github', link: 'https://github.com/muyangyan'}
- {icon: 'twitter', link: 'https://x.com/muyangyan'}
- {icon: 'instagram', link: 'https://www.instagram.com/muyang.yan/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/muyangyan/'}